import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <>
      <Head>
        <title>Childcare Costs in England</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.centered}>
            <p> Hello, I'm Evgeny. I am a polyglot software engineer and a dad. 
              I found out that childcare in London is extremely expensive and for busy parents calculating it can be frustrating,
              so i created this little  <Link href="/childcare/main"> tool</Link> that might help.</p>
      </main>
    </>
  )
}
